M48
; DRILL file {KiCad 9.0.3} date 2025-07-28T01:45:41+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-07-28T01:45:41+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.1299Y-2.9134
X3.1299Y-4.311
X5.2756Y-2.9134
X5.2756Y-4.311
M30
